
package workfinal;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JOptionPane;

public class Frm_login extends javax.swing.JFrame {

   
    public Frm_login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        name_f = new javax.swing.JTextField();
        telfiel = new javax.swing.JTextField();
        apellidofiel = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        password2 = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        boton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        boton_signup = new javax.swing.JButton();
        boton_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Already have an acount? Click Login");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 210, 20));

        email.setForeground(new java.awt.Color(153, 153, 153));
        email.setText("Email");
        email.setToolTipText("email here");
        email.setBorder(null);
        email.setCaretColor(new java.awt.Color(153, 255, 255));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 250, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setLabelFor(apellidofiel);
        jLabel13.setText("Apellido");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 354, -1, 30));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setLabelFor(telfiel);
        jLabel16.setText("Telefono");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, 20));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setLabelFor(name_f);
        jLabel17.setText("Nombre");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 324, -1, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Re-Password");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        username.setForeground(new java.awt.Color(153, 153, 153));
        username.setText("Username");
        username.setToolTipText("username here");
        username.setBorder(null);
        username.setCaretColor(new java.awt.Color(153, 255, 255));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 250, -1));

        name_f.setBorder(null);
        jPanel2.add(name_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 180, 20));

        telfiel.setBorder(null);
        jPanel2.add(telfiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 160, 20));

        apellidofiel.setBorder(null);
        apellidofiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidofielActionPerformed(evt);
            }
        });
        jPanel2.add(apellidofiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 180, 20));

        password.setToolTipText("password here");
        password.setBorder(null);
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 250, -1));

        password2.setToolTipText("password here");
        password2.setBorder(null);
        jPanel2.add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 250, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kenshin\\Desktop\\te\\Sign Up.png")); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, -1, -1));

        boton2.setBackground(new java.awt.Color(255, 255, 255));
        boton2.setForeground(new java.awt.Color(255, 255, 255));
        boton2.setContentAreaFilled(false);
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        jPanel2.add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 90, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kenshin\\Desktop\\te\\btnsignUp.png")); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 100, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kenshin\\Desktop\\te\\Email.png")); // NOI18N
        jLabel12.setLabelFor(email);
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kenshin\\Desktop\\te\\Password.png")); // NOI18N
        jLabel11.setLabelFor(password);
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kenshin\\Desktop\\te\\Username.png")); // NOI18N
        jLabel8.setLabelFor(username);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 60, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kenshin\\Desktop\\te\\Sign Up.png")); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 60, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kenshin\\Desktop\\te\\Login.png")); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 60, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kenshin\\Desktop\\te\\btnLoginSwitch.png")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 90, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kenshin\\Desktop\\te\\btnSignUpSwitch.png")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kenshin\\Desktop\\te\\Join Us.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 70, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kenshin\\Desktop\\te\\rightPanel.png")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 380, 440));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kenshin\\Desktop\\tumblr_94a1d9bb95e4ffb7510a6adb9f9a195b_80585a77_500.gif")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 370, 420));

        boton_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_signupActionPerformed(evt);
            }
        });
        jPanel2.add(boton_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 50, 30));

        boton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_loginActionPerformed(evt);
            }
        });
        jPanel2.add(boton_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 70, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -50, 820, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    


    
    
    
    
    
    
    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void boton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_loginActionPerformed
        setVisible(false);
        logi ma = new logi();
                    ma.setVisible(true);
                    ma.pack();
                    ma.setLocationRelativeTo(null);
    }//GEN-LAST:event_boton_loginActionPerformed

    private void boton_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_signupActionPerformed
        
            conexion objConexion= new conexion();
            
            String user = username.getText();
            String emails = email.getText();
            String pass = String.valueOf(password.getPassword());
            String pass2 = String.valueOf(password2.getPassword());
            String nombre = name_f.getText();
            String apellido = apellidofiel.getText();
            String tel = telfiel.getText();
            
            if(user.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add A Username");
            }
            
            else if(pass.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add A Password");
            }
            

            else if(emails.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add A Email");
            }
            else if(nombre.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add A name");
            }
            else if(apellido.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add A apellido");
            }
            else if(tel.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add A telefono");
            }
            else if(pass == null ? pass2 != null : !pass.equals(pass2))
            {
                JOptionPane.showMessageDialog(null, "La contraseña no coincide");
            }
            
            
            else {
                if (checkUsername(user)){
                    JOptionPane.showMessageDialog(null,"Este usuario ya existe");
                
            }
                else{
                    JOptionPane.showMessageDialog(null,"¡Usuario Creado!");
            
                    String strSentenciaInsert= String.format("insert into usuarios(user,password,email,nombre,apellido,telefono)"
                        + "values (\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",\"%s\")",user,pass,emails,nombre,apellido,tel);
                //Ejecutando sentencia.
                    objConexion.ejecutarSentenciaMYSQL(strSentenciaInsert);
                    
                    
                //Mostrando la interfaz de administración de usuarios y cerrando el de registro.
                    logi ma = new logi();
                
                    ma.pack();
                    ma.setLocationRelativeTo(null);
                    ma.setVisible(true);
                    this.setVisible(false);
                }
                    
                
                
            }
        
    }//GEN-LAST:event_boton_signupActionPerformed
    
   
    public boolean checkUsername(String username) 
    {
        
        
        
            boolean checkUser = false;
            conexion objConexion= new conexion();
            ResultSet rs = objConexion.consultarRegistros("SELECT user FROM usuarios WHERE user = '"+username+"'");
            
            
            
            
        try {
            if(rs.next())
            {
                checkUser = true;
            }
            else{
                checkUser = false;
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
            return checkUser;
         
    }
    
    
    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
        if(username.getText().trim().toLowerCase().equals("username")){
            username.setText("");
            username.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        
        username.setForeground(Color.gray);
    }//GEN-LAST:event_usernameFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        if(email.getText().trim().toLowerCase().equals("email")){
            email.setText("");
            email.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        
        email.setForeground(Color.gray);
    }//GEN-LAST:event_emailFocusLost

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
    conexion objConexion= new conexion();
            
            String user = username.getText();
            String emails = email.getText();
            String pass = String.valueOf(password.getPassword());
            String pass2 = String.valueOf(password2.getPassword());
            String nombre = name_f.getText();
            String apellido = apellidofiel.getText();
            String tel = telfiel.getText();
            if(user.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add A Username");
            }
            
            else if(pass.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add A Password");
            }
            
            else if(emails.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add A Email");
            }
            else if(pass == null ? pass2 != null : !pass.equals(pass2))
            {
                JOptionPane.showMessageDialog(null, "La contraseña no coincide");
            }
            else if(nombre.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add A name");
            }
            else if(apellido.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add A apellido");
            }
            else if(tel.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add A telefono");
            }
            
            
            else {
                if (checkUsername(user)){
                    JOptionPane.showMessageDialog(null,"Este usuario ya existe");
                
            }
                else{
                    JOptionPane.showMessageDialog(null,"¡Usuario Creado!");
            
                    String strSentenciaInsert= String.format("insert into usuarios(user,password,email,nombre,apellido,telefono)"
                        + "values (\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",\"%s\")",user,pass,emails,nombre,apellido,tel);
                //Ejecutando sentencia.
                    objConexion.ejecutarSentenciaMYSQL(strSentenciaInsert);
                    
                    
                //Mostrando la interfaz de administración de usuarios y cerrando el de registro.
                    logi ma = new logi();
                
                    ma.pack();
                    ma.setLocationRelativeTo(null);
                    ma.setVisible(true);
                    this.setVisible(false);
                }
                    
                
                
            }
    }//GEN-LAST:event_boton2ActionPerformed

    private void apellidofielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidofielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidofielActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidofiel;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton_login;
    private javax.swing.JButton boton_signup;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name_f;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password2;
    private javax.swing.JTextField telfiel;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
