
package workfinal;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kenshin
 */
public class tabla extends javax.swing.JFrame {
    DefaultTableModel modelo;
    /**
     * Creates new form tabla
     */
    public tabla() {
        initComponents();
        this.setLocationRelativeTo(null);
        String[] titulos = {"ID","User","Pasword","Email","Nombre","Apellido","Telefono"};
        modelo = new DefaultTableModel(null,titulos);
        jTable1.setModel(modelo);
        //Cargando los datos en mi tabla para que puedan ser mostrados al usuario.
        this.mostrarDataos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        eliminar_bo = new javax.swing.JButton();
        actu_botn = new javax.swing.JButton();
        agregar_bot = new javax.swing.JButton();
        logout_bo = new javax.swing.JButton();
        userfiel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailfiel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passfield = new javax.swing.JTextField();
        limp_bo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        name_f = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        apellidofiel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telfiel = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 790, 300));

        eliminar_bo.setText("Eliminar");
        eliminar_bo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_boActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar_bo, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 400, 90, -1));

        actu_botn.setText("Actualizar");
        actu_botn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actu_botnActionPerformed(evt);
            }
        });
        jPanel1.add(actu_botn, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 400, 100, -1));

        agregar_bot.setText("Agregar");
        agregar_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_botActionPerformed(evt);
            }
        });
        jPanel1.add(agregar_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 400, 100, -1));

        logout_bo.setText("Cerrar sesion");
        logout_bo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_boActionPerformed(evt);
            }
        });
        jPanel1.add(logout_bo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, -1));

        userfiel.setBorder(null);
        jPanel1.add(userfiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 130, -1));

        jLabel1.setLabelFor(userfiel);
        jLabel1.setText("User");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 20));

        jLabel2.setLabelFor(emailfiel);
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, 20));

        emailfiel.setBorder(null);
        jPanel1.add(emailfiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 190, -1));

        jLabel3.setLabelFor(passfield);
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, 20));

        passfield.setBorder(null);
        jPanel1.add(passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 160, -1));

        limp_bo.setText("Limpiar");
        limp_bo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limp_boActionPerformed(evt);
            }
        });
        jPanel1.add(limp_bo, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 400, 100, -1));

        jLabel4.setLabelFor(name_f);
        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        name_f.setBorder(null);
        jPanel1.add(name_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 130, -1));

        jLabel5.setLabelFor(apellidofiel);
        jLabel5.setText("Apellido");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, 20));

        apellidofiel.setBorder(null);
        jPanel1.add(apellidofiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 160, 20));

        jLabel6.setLabelFor(telfiel);
        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, 20));

        telfiel.setBorder(null);
        jPanel1.add(telfiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 140, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminar_boActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_boActionPerformed
       //Estableciendo conexión con mi Base De Datos sistema.
        conexion objConexion= new conexion();
        //Recuperando los datos.
        
        int fila = jTable1.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null,"Usuario no seleccionado");
        
        }else{
            int id = Integer.parseInt((String)jTable1.getValueAt(fila,0).toString());
            
        //Estableciendo mi sentencia DELETE para poder borrar los registros que contenga mi tabla usuario.
        String strSentenciaInsert= String.format("DELETE FROM usuarios WHERE id = %d",id);
        //Ejecutando sentencia...
        objConexion.ejecutarSentenciaMYSQL(strSentenciaInsert);
        //Actualizando tabla para que cargue nuevamente los registros.
        this.mostrarDataos();
        //Limpiando mis txtFields.
        this.limpiar();
        }
    }//GEN-LAST:event_eliminar_boActionPerformed

    private void agregar_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_botActionPerformed
        Agregar();
        this.mostrarDataos();
    }//GEN-LAST:event_agregar_botActionPerformed

    private void logout_boActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_boActionPerformed
        JOptionPane.showMessageDialog(null,"Sesion cerrada correctamente!");
        logi ma = new logi();
                
                    ma.pack();
                    ma.setLocationRelativeTo(null);
                    ma.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_logout_boActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null,"Usuario no seleccionado");
        
        }else{
            int id = Integer.parseInt((String)jTable1.getValueAt(fila,0).toString());
            String dn = (String)jTable1.getValueAt(fila,1);
            String nom = (String)jTable1.getValueAt(fila,3);
            String nombre = (String)jTable1.getValueAt(fila,4);
            String Apellido = (String)jTable1.getValueAt(fila,5);
            String Telefono = (String)jTable1.getValueAt(fila,6);
            
            
            userfiel.setText(dn);
            emailfiel.setText(nom);
            name_f.setText(nombre);
            apellidofiel.setText(Apellido);
            telfiel.setText(Telefono);
            
            
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void limp_boActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limp_boActionPerformed
           this.limpiar();     // TODO add your handling code here:
    }//GEN-LAST:event_limp_boActionPerformed

    private void actu_botnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actu_botnActionPerformed
        String user = userfiel.getText();
        String pass = passfield.getText();
        String email = emailfiel.getText();
        String name = name_f.getText();
        String apellido = apellidofiel.getText();
        String telefono = telfiel.getText();
        conexion objConexion= new conexion();
        //Recuperando los datos.
        
        int fila = jTable1.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null,"Usuario no seleccionado");
        
        }else{
            int id = Integer.parseInt((String)jTable1.getValueAt(fila,0).toString());
            
        //Estableciendo mi sentencia DELETE para poder borrar los registros que contenga mi tabla usuario.
        String strSentenciaInsert= String.format("update usuarios set user ='"+user+"',password='"+pass+"',email='"+email+"',nombre='"+name+"',apellido='"+apellido+"',telefono='"+telefono+"' WHERE id = '"+id+"'");
        //Ejecutando sentencia...
        objConexion.ejecutarSentenciaMYSQL(strSentenciaInsert);
        //Actualizando tabla para que cargue nuevamente los registros.
        this.mostrarDataos();
        //Limpiando mis txtFields.
        this.limpiar();
        }
    }//GEN-LAST:event_actu_botnActionPerformed
       
    void Agregar(){
        String user = userfiel.getText();
        String pass = passfield.getText();
        String email = emailfiel.getText();
        String nombre = name_f.getText();
        String apellido = apellidofiel.getText();
        String tel = telfiel.getText();
        
        if(user.equals("")||pass.equals("")||email.equals("")){
               JOptionPane.showMessageDialog(null,"Campos vacios...!!!");
        }else{
            String strSentenciaInsert= String.format("insert into usuarios(user,password,email,nombre,apellido,telefono)"
                        + "values (\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",\"%s\")",user,pass,email,nombre,apellido,tel);
                //Ejecutando sentencia.
                    
            try{
                conexion con = new conexion();
                con.ejecutarSentenciaMYSQL(strSentenciaInsert);
                JOptionPane.showMessageDialog(null,"Registros agregados correctamente!");
            }catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        
        }
    
    
    
    }
    
    
    
    
    
    
     public void mostrarDataos(){
        //Preprando mis registros en mi tabla...
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        //Estableciendo conexión en mi base de datos.
        conexion objConexion= new conexion();
        //Try catch para el manejo de posibles errores.
          try {
            //Realizando consulta para traer todos los registros que esten en mi tabla usuario de mi base de datos sistema.
            ResultSet resultado = objConexion.consultarRegistros("SELECT * FROM usuarios");
            //Tomando todos los registros y guardandolo en un object para luego mostarlos en mi tabla del programa...
            while (resultado.next()) {
                System.out.println(resultado.getString("id"));
                System.out.println(resultado.getString("user"));
                System.out.println(resultado.getString("password"));
                System.out.println(resultado.getString("email"));
                System.out.println(resultado.getString("nombre"));
                System.out.println(resultado.getString("apellido"));
                System.out.println(resultado.getString("telefono"));
                Object[] oUsuario={resultado.getString("id"),resultado.getString("user"),resultado.getString("password"),resultado.getString("email"),resultado.getString("nombre"),resultado.getString("apellido"),resultado.getString("telefono")};
                modelo.addRow(oUsuario);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        
        
    }
    
    //Método para limpiar los datos que contengan escritos mis txtFields.
    public void limpiar(){
    
        userfiel.setText("");
        emailfiel.setText("");
        passfield.setText("");
        name_f.setText("");
        apellidofiel.setText("");
        telfiel.setText("");
        
     
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabla().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actu_botn;
    private javax.swing.JButton agregar_bot;
    private javax.swing.JTextField apellidofiel;
    private javax.swing.JButton eliminar_bo;
    private javax.swing.JTextField emailfiel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton limp_bo;
    private javax.swing.JButton logout_bo;
    private javax.swing.JTextField name_f;
    private javax.swing.JTextField passfield;
    private javax.swing.JTextField telfiel;
    private javax.swing.JTextField userfiel;
    // End of variables declaration//GEN-END:variables
}
